### ISSUE TITLE
RuntimeError: Not compiled with CUDA support

### ISSUE THREAD

**Issue by pstansfeld** [zrqiao/NeuralPLexer#25]
* PIGT version:
* Python version: 3.10.14
* Operating System: Rocky Linux

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did
```
python neuralplexer/inference.py --task=batched_structure_sampling --input-receptor "input.pdb" --input-ligand "ligand.sdf" --out-path "test" --model-checkpoint "neuralplexermodels_downstream_datasets_predictions/models/complex_structure_prediction.ckpt" --n-samples 16 --chunk-size 4 --num-steps=40 --cuda --sampler=langevin_simulated_annealing
```

```
  _C._set_default_tensor_type(t)
Traceback (most recent call last):
  File "/home/chem/lfsmgr/NeuralPLexer/neuralplexer/inference.py", line 675, in <module>
    main()
  File "/home/chem/lfsmgr/NeuralPLexer/neuralplexer/inference.py", line 655, in main
    multi_pose_sampling(
  File "/home/chem/lfsmgr/NeuralPLexer/neuralplexer/inference.py", line 182, in multi_pose_sampling
    output_struct = model.sample_pl_complex_structures(
  File "/home/chem/lfsmgr/NeuralPLexer/neuralplexer/model/wrappers.py", line 3104, in sample_pl_complex_structures
    batch = self.forward(
  File "/home/chem/lfsmgr/NeuralPLexer/neuralplexer/model/wrappers.py", line 187, in forward
    batch = self._run_encoder_stack(
  File "/home/chem/lfsmgr/NeuralPLexer/neuralplexer/model/wrappers.py", line 457, in _run_encoder_stack
    self._initialize_protatm_indexer_and_embeddings(batch)
  File "/home/chem/lfsmgr/NeuralPLexer/neuralplexer/model/wrappers.py", line 1590, in _initialize_protatm_indexer_and_embeddings
    self._standard_aa_molgraph_featset = self.ligand_encoder(
  File "/home/chem/lfsmgr/miniforge3/envs/neuralplexer_dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chem/lfsmgr/miniforge3/envs/neuralplexer_dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chem/lfsmgr/NeuralPLexer/neuralplexer/model/mht_encoder.py", line 210, in forward
    _, merged_node_attr, merged_edge_attr = self.graph_transformer_stacks[
  File "/home/chem/lfsmgr/miniforge3/envs/neuralplexer_dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chem/lfsmgr/miniforge3/envs/neuralplexer_dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chem/lfsmgr/NeuralPLexer/neuralplexer/model/modules.py", line 169, in forward
    out_a, (edge_index, alpha) = self.conv(
  File "/home/chem/lfsmgr/miniforge3/envs/neuralplexer_dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/chem/lfsmgr/miniforge3/envs/neuralplexer_dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chem/lfsmgr/NeuralPLexer/neuralplexer/model/modules.py", line 79, in forward
    attended_values = self.message(key, query, value, edge_attr, edge_index)
  File "/home/chem/lfsmgr/NeuralPLexer/neuralplexer/model/modules.py", line 111, in message
    alpha = segment_softmax(_alpha_z, index[1], query.shape[0])
  File "/home/chem/lfsmgr/NeuralPLexer/neuralplexer/model/common.py", line 77, in segment_softmax
    src_max, _ = scatter_max(src, dst_idx, dim=0, dim_size=dst_size)
  File "/home/chem/lfsmgr/miniforge3/envs/neuralplexer_dev/lib/python3.10/site-packages/torch_scatter/scatter.py", line 72, in scatter_max
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
  File "/home/chem/lfsmgr/miniforge3/envs/neuralplexer_dev/lib/python3.10/site-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Not compiled with CUDA support

```

**Comment by amorehead** [comment]
This means that `torch_scatter` didn't include its CUDA headers when it was installed. This is most likely due to Conda fetching the generic (CPU) version of `torch_scatter` which doesn't include CUDA support. I recommend uninstalling torch_scatter with `conda uninstall torch_scatter` and then reinstalling it with CUDA support following: https://github.com/rusty1s/pytorch_scatter?tab=readme-ov-file#anaconda

**Comment by pstansfeld** [comment]
Thanks @amorehead, that solved it perfectly following your instructions and then:
```
conda install pytorch-scatter -c pyg
```
